In [34]:
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree 
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [35]:
df = pd.read_csv("winequality_red.csv")

In [36]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [37]:
df.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [39]:
df.isnull().any().sum()

0

In [40]:
x = df.drop("quality", axis = 1)

In [41]:
y = df["quality"]

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 20)

In [43]:
knn = KNeighborsClassifier()

In [44]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [45]:
knn.predict(x_test)

array([6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 5, 6, 6, 4, 6,
       6, 5, 7, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 7, 6, 5, 5, 6, 5, 5, 6, 5,
       7, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5, 5,
       5, 5, 7, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 5, 4, 6, 5, 5,
       5, 5, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 5, 7, 4, 6, 6, 6, 5, 7, 6,
       5, 6, 7, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5,
       5, 5, 5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 4, 6, 5, 6, 6, 5, 6, 6,
       6, 5, 5, 6, 5, 6, 6, 5, 6, 5, 5, 7, 5, 5, 6, 5, 5, 7, 5, 6, 6, 7,
       5, 7, 5, 5, 7, 7, 7, 5, 6, 6, 6, 5, 7, 5, 6, 5, 6, 5, 5, 5, 5, 5,
       6, 6, 6, 5, 7, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6,
       5, 6, 6, 6, 6, 7, 5, 5, 6, 6, 5, 6, 7, 6, 6, 5, 7, 5, 6, 5, 5, 7,
       6, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5, 5,
       6, 5, 5, 5, 6, 3, 6, 6, 7, 6, 5, 7, 7, 5, 5, 5, 6, 6, 6, 6, 5, 5,
       5, 6, 5, 6, 6, 6, 5, 7, 6, 6, 6, 5, 6, 6, 5,

In [46]:
knn.score(x_test, y_test)

0.5175

In [86]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 10,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 21,
 'p': 1,
 'weights': 'distance'}

In [90]:
param = {
    'n_neighbors' : [3,5,7,9,12,13,15,17,21],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [10, 15, 20, 25, 30, 35, 40, 45, 50],
    'p': [1,2],
    'weights':['uniform', 'distance']
}


In [91]:
knn_grid = GridSearchCV(knn, param_grid = param)

In [92]:
knn_grid.fit(x_train, y_train)

KeyboardInterrupt: 

In [50]:
knn_grid.best_params_

{'n_neighbors': 17}

In [80]:
knn = KNeighborsClassifier(n_neighbors = 21, p = 1, weights = 'distance', leaf_size = 10, algorithm  = 'auto')

In [81]:
knn.fit(x_train, y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance')

In [82]:
knn.score(x_test, y_test)

0.6325

Model score improved by 4%. when p = 1 accurcay improved by 5%.

In [94]:
import pickle

pickle.dump(knn, open('knn.pkl', 'wb'))

In [95]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 9452-2BAA

 Directory of C:\Users\Hp\Desktop\ML and DL\ML algorithms

10-10-2021  16:05    <DIR>          .
10-10-2021  16:05    <DIR>          ..
10-10-2021  16:05    <DIR>          .ipynb_checkpoints
30-08-2021  16:30    <DIR>          admission_lr_model
30-08-2021  18:10               560 admission_lr_model.pickle
30-08-2021  15:00            12,903 Admission_Predict.csv
30-08-2021  15:13            16,085 Admission_Prediction.csv
28-08-2021  23:08           522,048 ai4i2020.csv
10-10-2021  15:24        12,310,223 Decision tree practical .ipynb
05-10-2021  18:36        11,932,728 DecisionTree analysis on wine quality dataset.ipynb
26-09-2021  16:14                 0 df_entropy_meta.dot
26-09-2021  16:14                 0 df_entropy_meta.dot1
03-10-2021  16:01           124,452 dt_model.png
09-10-2021  15:39           137,798 dt_model_1.png
30-09-2021  19:31           140,001 EDA Thyroid Detection.ipynb
30-09-2021  14:39      

In [96]:
knn.predict(x_test)

array([6, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6,
       6, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 7, 6, 5, 6, 6, 5, 5, 6, 5,
       7, 5, 6, 6, 6, 6, 7, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5,
       5, 5, 5, 6, 5, 6, 6, 6, 5, 6, 7, 5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 6,
       5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6, 7, 6, 5,
       5, 6, 6, 5, 6, 6, 5, 7, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5, 6,
       6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 7, 5, 5, 5, 5, 5, 6, 5, 6, 6, 6,
       6, 6, 5, 5, 7, 6, 7, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 5, 7, 5, 6,
       6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 5,
       5, 5, 5, 6, 6, 7, 5, 6, 7, 6, 5, 5, 7, 6, 5, 5, 6, 6, 6, 5, 6, 7,
       7, 5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 7, 5, 5, 6, 6, 5, 5, 5,
       6, 6, 6, 7, 5, 5, 5, 7, 7, 6, 5, 7, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 7, 7, 5, 5, 5, 6, 5, 5,

In [99]:
knn.predict([x_test.iloc[0]])

array([6], dtype=int64)

In [100]:
[x_test.iloc[0]]

[fixed acidity            7.10000
 volatile acidity         0.27000
 citric acid              0.60000
 residual sugar           2.10000
 chlorides                0.07400
 free sulfur dioxide     17.00000
 total sulfur dioxide    25.00000
 density                  0.99814
 pH                       3.38000
 sulphates                0.72000
 alcohol                 10.60000
 Name: 1508, dtype: float64]

In [101]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]